version: 0.2

env:
  variables:
    TF_VERSION: "1.14.8"
    TF_OS: linux
    TF_ARCH: arm64
    TF_EXEC_PATH: terraform
phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -sL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${TF_OS}_${TF_ARCH}.zip > terraform.zip
      - unzip terraform.zip -d /tmp
      - chmod +x /tmp/terraform
      - export PATH=/tmp:$PATH
      - terraform version
  pre_build:
    commands:
      - cd ${TF_EXEC_PATH}
      - echo Initializing Terraform...
      - terraform init
        -lockfile=readonly
        -backend-config="bucket=${TF_STATE_BUCKET}"
        -backend-config="key=${PREFIX}-tracis.tfstate"
        -backend-config="region=${AWS_REGION}"
        -backend-config="use_lockfile=true"
  build:
    commands:
      - echo "Executing terraform ${TF_ACTION} (desired count = ${DESIRED_COUNT})..."
      - terraform ${TF_ACTION}
        -auto-approve
        -var="ecs_service_desired_count=${DESIRED_COUNT}"
        -var="prefix=${PREFIX}"
        -var="subnet_ids=${SUBNET_IDS}"
        -var="mysql_endpoint=${MYSQL_ENDPOINT}"
        -var="mysql_port=${MYSQL_PORT}"
        -var="mysql_db_name=${MYSQL_DB_NAME}"
        -var="mysql_security_group_ids=${MYSQL_SECURITY_GROUP_IDS}"
        -var="mysql_secret_arn=${MYSQL_SECRET_ARN}"
        -var="slack_secret_arn=${SLACK_SECRET_ARN}"
        -var="bedrock_model_id=${BEDROCK_MODEL_ID}"
        -var="max_tokens=${MAX_TOKENS}"
        -var="orchestrator_agent_image_url=${ORCHESTRATOR_AGENT_IMAGE_URL}"
        -var="tool_agent_image_url=${TOOL_AGENT_IMAGE_URL}"
        -var="cloudwatch_mcp_image_url=${CLOUDWATCH_MCP_IMAGE_URL}"
        -var="mysql_mcp_image_url=${MYSQL_MCP_IMAGE_URL}"
        -var="enable_fargate_spot=${USE_FARGATE_SPOT}"

  post_build:
    commands:
      - |
        if [ "${TF_ACTION}" = "destroy" ]; then
          echo Deleting Terraform state file from S3...

          aws s3api list-object-versions \
            --bucket ${TF_STATE_BUCKET} \
            --prefix "${PREFIX}-tracis.tfstate" \
            --query '{Objects: Versions[].{Key:Key,VersionId:VersionId}}' \
            --output json > versions.json
          if [ "$(jq '.Objects | length' versions.json)" != "0" ]; then
            aws s3api delete-objects \
              --bucket ${TF_STATE_BUCKET} \
              --delete file://versions.json
          fi

          aws s3api list-object-versions \
            --bucket ${TF_STATE_BUCKET} \
            --prefix "${PREFIX}-tracis.tfstate" \
            --query '{Objects: DeleteMarkers[].{Key:Key,VersionId:VersionId}}' \
            --output json > delete-markers.json
          if [ "$(jq '.Objects | length' delete-markers.json)" != "0" ]; then
            aws s3api delete-objects \
              --bucket ${TF_STATE_BUCKET} \
              --delete file://delete-markers.json
          fi
        fi
