[SERVICE]
    # Flush logs every 5 seconds
    Flush 5
    # Wait 30 seconds during shutdown to flush remaining logs
    Grace 30
    # Minimum seconds between retries
    scheduler.base 5
    # Maximum seconds between retries (exponential backoff cap)
    scheduler.cap 60
    # Built-in HTTP server for monitoring
    # https://docs.fluentbit.io/manual/administration/monitoring
    HTTP_Server On
    HTTP_Listen 127.0.0.1
    HTTP_Port 2020
    Parsers_File /fluent-bit/etc/parsers.conf

# Parse JSON logs only
# https://docs.fluentbit.io/manual/data-pipeline/filters/parser
[FILTER]
    Name parser
    Match *-firelens-*
    Key_Name log
    Parser json
    Reserve_Data true

# Route statistics logs
# https://docs.fluentbit.io/manual/data-pipeline/filters/rewrite-tag
[FILTER]
    Name rewrite_tag
    # NOTE: default tag = '<container name>-firelens-<task id>'
    Match *-firelens-*
    Rule transfer_to ^BTM$ stats false

#https://docs.fluentbit.io/manual/data-pipeline/outputs/http
[OUTPUT]
    Name http
    Match stats
    host customer.tracis.ai
    port 443
    tls on
    uri /v1/logs
    header x-transfer-to btm-tracis-statistics-api
    format json
    retry_limit 15

# https://docs.fluentbit.io/manual/data-pipeline/outputs/cloudwatch
[OUTPUT]
    Name cloudwatch_logs
    Match *-firelens-*
    region ${AWS_REGION}
    log_group_name ${CW_LOG_GROUP_NAME}
    log_stream_prefix ecs-
    log_stream_template /ecs/agent/$container_id
    log_key log
    retry_limit 15
